#!/usr/bin/env bash
set -euo pipefail

# -------------------------------------------------------------------- Paths --

# Path to direcrory, in which current script resides
HERE=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Dir with configuration files
CONF=$HERE/conf

# ----------------------------------------------------------------- Dotfiles --

function deploy {
    mkdir -p `dirname $2`
    ln -sf $1 $2
}

deploy $CONF/ssh       ~/.ssh/config
deploy $CONF/fonts     ~/.config/fontconfig/fonts.conf
deploy $CONF/htop      ~/.config/htop/htoprc
deploy $CONF/i3/config ~/.config/i3/config
deploy $CONF/i3/status ~/.config/i3/status
deploy $CONF/git       ~/.gitconfig
deploy $CONF/xprofile  ~/.xprofile
deploy $CONF/vim       ~/.vim
deploy $CONF/vim/vimrc ~/.vimrc

chmod -R u=rwX,go= ~/.ssh

# ----------------------------------------------------------------- Packages --

apt-get install \
    subversion \
    vim \
    openssh-client \
    openssh-server \
    rsync \
    xorg \
    i3 \
    i3status \
    htop \
    arandr \
    network-manager \
    network-manager-gnome \
    binutils \
    gcc-4.8 \
    iceweasel \
    cmake \
    evince \
    feh \
    fontconfig \
    flashplugin-nonfree \
    ttf-mscorefonts-installer \
    gdb \
    graphviz \
    gnome \
    python3.4 \
    ranger \
    unrar \
    unzip \
    xclip \
    xserver-xorg \
    xterm \
    curl \
    wget
    #inkscape \
    #gimp \
    #texlive

