set nocompatible
source ~/.vim/bundle/pathogen-2.0/pathogen.vim
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

autocmd BufWritePre * :%s/\s\+$//e

call pathogen#infect('~/.vim/bundle') " activate Pathogen
set ttyfast

" --------------------------------------------- GUI, colors, line numbering --
set guifont=Monospace\ 8
set guioptions-=aegimrLtT

syntax on               " turn on syntax highlighting
set number              " turn on line numbering
set colorcolumn=81,101  " set right margin at 80/100 columns
set synmaxcol=200       " highlight at most 200 chars
                        " (100 columns x 2 chars per UTF-8 symbol)

set t_Co=256            " tell vim, that terminal supports 256 colors
colorscheme desert      "   set color scheme

" ----------------------------------------------- Wrapping, tabs and spaces --
set wrap
setlocal wrap linebreak nolist
set virtualedit=
setlocal display+=lastline
noremap  <buffer> <silent> <Up>   gk
noremap  <buffer> <silent> <Down> gj
noremap  <buffer> <silent> <Home> g<Home>
noremap  <buffer> <silent> <End>  g<End>
inoremap <buffer> <silent> <Up>   <C-o>gk
inoremap <buffer> <silent> <Down> <C-o>gj
inoremap <buffer> <silent> <Home> <C-o>g<Home>
inoremap <buffer> <silent> <End>  <C-o>g<End>

" tabs and spaces
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" -------------------------------------------------------------------- Misc --
set nobackup    " turn off backup files
set noundofile  " turn off persistend undo files
set noswapfile  " turn off swap files

" ------------------------------------------------------------ Key bindings --
nmap <C-N>v :NERDTree<cr>
vmap <C-N>v <esc>:NERDTree<cr>i
imap <C-N>v <esc>:NERDTree<cr>i

nmap <C-N>x :NERDTreeClose<cr>
vmap <C-N>x <esc>:NERDTreeClose<cr>i
imap <C-N>x <esc>:NERDTreeClose<cr>i

nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

nnoremap <C-Down> :m+<CR>==
nnoremap <C-Up> :m-2<CR>==
inoremap <C-Down> <Esc>:m+<CR>==gi
inoremap <C-Up> <Esc>:m-2<CR>==gi
vnoremap <C-Down> :m'>+<CR>gv=gv
vnoremap <C-Up> :m-2<CR>gv=gv
vnoremap <Tab> >
vnoremap <S-Tab> <
